server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zx123456
    url: jdbc:mysql://127.0.0.1:3306/dianping?characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF8

  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

admin:
  email: 123456
  encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==

#申明es服务地址
elasticsearch:
  ip: 127.0.0.1:9200
#elasticsearch:
#  ip1: 127.0.0.1:9200
#  ip2: 127.0.0.1:9201
#  ip3: 127.0.0.1:9202